### ISSUE TITLE
Add Bootstrap or something else for managing styles, classes and all the CSS

### ISSUE THREAD

**Issue by bebatut** [bebatut/galaxy_mentor_network#11]

**Comment by Chinonyemildred** [comment]
Okay, I'll work on it. Thank you:)

**Comment by Chinonyemildred** [comment]
<img width="957" alt="Screenshot 2022-02-01 174819" src="https://user-images.githubusercontent.com/82679007/152022896-1d84bc47-35cf-4cba-91dc-8fe29bc509a6.png">

I got this after trying to install bootstrap.

**Comment by bebatut** [comment]
What commands did you run?

**Comment by rahmot** [comment]
Gridsome doesn't have the Bootstrap plugin yet. Maybe that was why it wasn't working. But it [BootstrapVue](https://bootstrap-vue.js.org/) and you can install it by using `npm i vue bootstrap-vue bootstrap`.

**Comment by Chinonyemildred** [comment]
> What commands did you run?

I ran `gridsome create bootstrap jquery popper.js --save`

**Comment by Chinonyemildred** [comment]
> Gridsome doesn't have the Bootstrap plugin yet. Maybe that was why it wasn't working. But it [BootstrapVue](https://bootstrap-vue.js.org/) and you can install it by using `npm i vue bootstrap-vue bootstrap`.

Yeah, you're right. I saw this when I was researching last night and I shared a link with @bebatut  but it was titled gridsome bootstrap starter.

Let me check this one out. Thank you:)

**Comment by bebatut** [comment]
We added Bootstrap
