### ISSUE TITLE
Deploy using Netlify to get preview

### ISSUE THREAD

**Issue by bebatut** [bebatut/galaxy_mentor_network#12]

**Comment by rahmot** [comment]
Great, I will do this when we have implemented the home page.

**Comment by bebatut** [comment]
I think I will need to do it as I am the one with the rights there

**Comment by rahmot** [comment]
Okay! Thought anybody can deploy the website on Netlify by importing the project from Git repo since the GMN repo is public. What do you think?

**Comment by bebatut** [comment]
No only the owner of the repository

**Comment by bebatut** [comment]
It works now: see #13
