### ISSUE TITLE
Help Needed!

### ISSUE THREAD

**Issue by Chinonyemildred** [bebatut/galaxy_mentor_network#23]
<img width="960" alt="Screenshot 2022-02-04 190558" src="https://user-images.githubusercontent.com/82679007/152580613-2fc0ece8-4ed7-4df7-9f38-a220bb5ebe19.png">

Please how do I clear out these '14 commits'? I tried @bebatut 's method this evening....I `git checkout main`>`git pull origin main`>`git checkout -b branch name` before I made my edits..

I also did `git log` and only the recent commit I did was in the log yet when I open the commit here, it was still carrying these 14 baggage.

Stackoverflow responses suggested `git reset --hard HEAD`, it didn't help much. 

Please any clues on how to delete them entirely?

**Comment by Chinonyemildred** [comment]
I clicked on contribute and saw that I have to create a PR...but these commits are kind of stale. I tried to delete from there but I couldn't

**Comment by Chinonyemildred** [comment]
<img width="958" alt="Screenshot 2022-02-04 192806" src="https://user-images.githubusercontent.com/82679007/152583281-d443d1e9-175a-4635-a54f-a301a58b7a4e.png">

can the problem be the fact that I deleted the branches?

**Comment by rahmot** [comment]
> <img alt="Screenshot 2022-02-04 192806" width="958" src="https://user-images.githubusercontent.com/82679007/152583281-d443d1e9-175a-4635-a54f-a301a58b7a4e.png">
> 
> can the problem be the fact that I deleted the branches?

I think so. The branch isn't again, you can probably ignore it and start afresh.

**Comment by Chinonyemildred** [comment]
@rahmot yea, I tried starting afresh, just like you and Assunta directed a few minutes ago. I still have the commits in the new branch

**Comment by Chinonyemildred** [comment]
Thank you all for your help! It has been resolved
